language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblapack-dev libopenblas-dev

# Install packages
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install --upgrade numpy
  - pip install --upgrade scipy
  - pip install --upgrade pandas
  - pip install --upgrade coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=hspfbintoolbox --cover-branches --cover-erase

after_success:
  - coveralls
